// Generated by CoffeeScript 1.6.2
(function() {
  exports.serial = function(steps, finalCallback) {
    var index, processNextStep;

    index = 0;
    processNextStep = function() {
      if (steps[index] == null) {
        return typeof finalCallback === "function" ? finalCallback(null) : void 0;
      }
      return steps[index++](function(err) {
        if (err != null) {
          return typeof finalCallback === "function" ? finalCallback(err) : void 0;
        } else {
          return processNextStep();
        }
      });
    };
    return processNextStep();
  };

}).call(this);
